from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bad784af76e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    op.drop_index('id', table_name='users')
    op.drop_table('users')

    op.create_table('users',
                    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
                    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=128), nullable=False),
                    sa.Column('old_fraction', mysql.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('fraction', mysql.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('update_time', mysql.TIMESTAMP(), nullable=False),
                    sa.Column('consecutive_sign_in', mysql.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('last_sign_in', mysql.TIMESTAMP(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_unicode_520_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_index('id', 'users', ['id'], unique=False)

    op.create_table('log',
                    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=128), nullable=False),
                    sa.Column('event_time', mysql.TIMESTAMP(), nullable=False),
                    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False),
                    sa.Column('event', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=128), nullable=False),
                    mysql_collate='utf8mb4_unicode_520_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_foreign_key('fk_log_user_id', 'log', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_log_user_id', 'log', type_='foreignkey')

    op.drop_table('log')

    op.create_table('users',
                    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
                    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=128), nullable=False),
                    sa.Column('old_fraction', mysql.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('fraction', mysql.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('update_time', mysql.TIMESTAMP(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_unicode_520_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_index('id', 'users', ['id'], unique=False)
    # ### end Alembic commands ###
